-- liquibase formatted sql

-- changeset hp-omen:1771177328242-1 splitStatements:false
CREATE TABLE LOCATION (ID BIGINT AUTO_INCREMENT NOT NULL, LATITUDE FLOAT(53) NULL, LONGITUDE FLOAT(53) NULL, NAME VARCHAR(255) NULL, REGION VARCHAR(255) NULL, CONSTRAINT LOCATIONPK PRIMARY KEY (ID));

-- changeset hp-omen:1771177328242-2 splitStatements:false
CREATE TABLE USER (ID BIGINT AUTO_INCREMENT NOT NULL, EMAIL VARCHAR(255) NULL, FIRST_NAME VARCHAR(255) NULL, MIDDLE_NAME VARCHAR(255) NULL, PASSWORD VARCHAR(255) NULL, SURNAME VARCHAR(255) NULL, USERNAME VARCHAR(255) NULL, CONSTRAINT USERPK PRIMARY KEY (ID));

-- changeset hp-omen:1771177328242-3 splitStatements:false
CREATE TABLE USER_LOCATION (USER_ID BIGINT NOT NULL, LOCATION_ID BIGINT NOT NULL);

-- changeset hp-omen:1771177328242-4 splitStatements:false
ALTER TABLE USER_LOCATION ADD CONSTRAINT location_id_key FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID);

-- changeset hp-omen:1771177328242-5 splitStatements:false
ALTER TABLE USER_LOCATION ADD CONSTRAINT user_id_key FOREIGN KEY (USER_ID) REFERENCES USER (ID);